float64 left_front_wheel_encoder_imp    #ID31: rotating wheel ( imp / s) * 100; 1 revolution of the wheel equals 54 pulses
float64 right_front_wheel_encoder_imp   #ID31: rotating wheel ( imp / s) * 100; 1 revolution of the wheel equals 54 pulses
float64 left_rear_wheel_encoder_imp     #ID31: rotating wheel ( imp / s) * 100; 1 revolution of the wheel equals 54 pulses
float64 right_rear_wheel_encoder_imp    #ID31: rotating wheel ( imp / s) * 100; 1 revolution of the wheel equals 54 pulses

float64 right_front_wheel_turn_angle_rad   
float64 left_front_wheel_turn_angle_rad    
float64 right_rear_wheel_turn_angle_rad    
float64 left_rear_wheel_turn_angle_rad     

#left -90 degrees; max turn right 90 degrees
int32 right_front_wheel_rotational_speed_rad_s
int32 left_front_wheel_rotational_speed_rad_s   #ID32: rotational speed( rad/s );
int32 right_rear_wheel_rotational_speed_rad_s     
int32 left_rear_wheel_rotational_speed_rad_s     