int64 engine_rotation_speed_rpm     # ID51:  The value of the rotational speed of the combustion engine
bool engine_running                   # ID51:  0 - off; 1 - the engine is running
int32 engine_coolant_temp_celsius   # ID51:  0 - 100 - value determining the temperature ( o C )
int32 engine_fuel_level_percent     # ID51:  Value specifying % of tank filling
int32 engine_oil_pressure_bar       # ID51:  0-100 (100 means 10 bar)

