bool left_front_turn_failed    #ID99: 0 - correct operation; 1 - faulty sensor or connection
bool right_front_turn_failed   #ID99: 0 - correct operation; 1 - faulty sensor or connection
bool left_rear_turn_failed     #ID99: 0 - correct operation; 1 - faulty sensor or connection
bool right_rear_turn_failed    #ID99: 0 - correct operation; 1 - faulty sensor or connection
bool tool_vertical_actuator_failed    #ID99: 0 - correct operation; 1 - faulty sensor or connection
bool tool_horizontal_actuator_failed  #ID99: 0 - correct operation; 1 - faulty sensor or connection
bool tool_level_sensor_failed         #ID99: 0 - correct operation; 1 - faulty sensor or connection