bool enable_foliar_sprayer_section1    #ID12 ; 0 - closed; 1 - open
bool enable_foliar_sprayer_section2    #ID12 ; 0 - closed; 1 - open 
bool enable_foliar_sprayer_section3    #ID12 ; 0 - closed; 1 - open
bool enable_foliar_sprayer_section4    #ID12 ; 0 - closed; 1 - open
   
bool enable_arable_sprayer_section1    #ID12 ; 0 - closed; 1 - open
bool enable_arable_sprayer_section2    #ID12 ; 0 - closed; 1 - open
bool enable_arable_sprayer_section3    #ID12 ; 0 - closed; 1 - open
bool enable_arable_sprayer_section4    #ID12 ; 0 - closed; 1 - open